// Array de materias de Ingeniería Informática (plan 2/25)
const materiasInformatica = [
  { "nro": 1, "nombre": "Introducción al Cálculo", "anio": 1, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [], "req_aprob_cursar": [], "req_aprob_rendir": [] },
  { "nro": 2, "nombre": "Álgebra I", "anio": 1, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [], "req_aprob_cursar": [], "req_aprob_rendir": [] },
  { "nro": 3, "nombre": "Resolución de Problemas y Algoritmos", "anio": 1, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [], "req_aprob_cursar": [], "req_aprob_rendir": [] },
  { "nro": 4, "nombre": "Programación I", "anio": 1, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [3], "req_aprob_cursar": [], "req_aprob_rendir": [3] },
  { "nro": 5, "nombre": "Matemática Discreta", "anio": 1, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [2], "req_aprob_cursar": [], "req_aprob_rendir": [2] },
  { "nro": 6, "nombre": "Cálculo I", "anio": 1, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [1], "req_aprob_cursar": [], "req_aprob_rendir": [1] },
  { "nro": 7, "nombre": "Álgebra II", "anio": 1, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [2], "req_aprob_cursar": [], "req_aprob_rendir": [2] },
  { "nro": 8, "nombre": "Probabilidad y Estadística", "anio": 2, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [5], "req_aprob_cursar": [], "req_aprob_rendir": [5] },
  { "nro": 9, "nombre": "Inglés", "anio": 2, "cuatrimestre": "A", "tipo": "obligatoria", "req_reg_cursar": [3], "req_aprob_cursar": [], "req_aprob_rendir": [3] },
  { "nro": 10, "nombre": "Programación II", "anio": 2, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [4], "req_aprob_cursar": [1], "req_aprob_rendir": [4] },
  { "nro": 11, "nombre": "Organización y Arquitectura de Computadoras", "anio": 2, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [4], "req_aprob_cursar": [3], "req_aprob_rendir": [4] },
  { "nro": 12, "nombre": "Programación III", "anio": 2, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [10], "req_aprob_cursar": [3], "req_aprob_rendir": [10] },
  { "nro": 13, "nombre": "Estructuras de Datos y Algoritmos", "anio": 2, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [4, 8], "req_aprob_cursar": [], "req_aprob_rendir": [4, 8] },
  { "nro": 14, "nombre": "Física", "anio": 2, "cuatrimestre": "A", "tipo": "obligatoria", "req_reg_cursar": [2, 6], "req_aprob_cursar": [1], "req_aprob_rendir": [2] },
  { "nro": 15, "nombre": "Ingeniería de Software I", "anio": 3, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [10], "req_aprob_cursar": [4], "req_aprob_rendir": [10] },
  { "nro": 16, "nombre": "Ética y Legislación", "anio": 3, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [10], "req_aprob_cursar": [4], "req_aprob_rendir": [10] },
  { "nro": 17, "nombre": "Base de Datos", "anio": 3, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [13], "req_aprob_cursar": [4], "req_aprob_rendir": [13] },
  { "nro": 18, "nombre": "Modelos y Simulación", "anio": 3, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [8, 10], "req_aprob_cursar": [6], "req_aprob_rendir": [8, 10] },
  { "nro": 19, "nombre": "Fundamentos de Computación", "anio": 3, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [13], "req_aprob_cursar": [2, 5], "req_aprob_rendir": [] },
  { "nro": 20, "nombre": "Ingeniería de Software II", "anio": 3, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [15, 17], "req_aprob_cursar": [10], "req_aprob_rendir": [15, 17] },
  { "nro": 21, "nombre": "Laboratorio de Tecnologías", "anio": 3, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [12, 15, 17], "req_aprob_cursar": [10], "req_aprob_rendir": [12, 15, 17] },
  { "nro": 22, "nombre": "Redes de Computadoras", "anio": 3, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [10, 11], "req_aprob_cursar": [5], "req_aprob_rendir": [10, 11] },
  { "nro": 23, "nombre": "Sistemas Operativos", "anio": 3, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [11, 18], "req_aprob_cursar": [5], "req_aprob_rendir": [11, 18] },
  { "nro": 24, "nombre": "Análisis Numérico", "anio": 3, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [10], "req_aprob_cursar": [6, 7], "req_aprob_rendir": [10] },
  { "nro": 25, "nombre": "Planeamiento Estratégico de Sistemas de Información", "anio": 4, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [20], "req_aprob_cursar": [], "req_aprob_rendir": [20] },
  { "nro": 26, "nombre": "Sistemas Críticos", "anio": 4, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [20, 24], "req_aprob_cursar": [12, 15], "req_aprob_rendir": [] },
  { "nro": 27, "nombre": "Ingeniería Web", "anio": 4, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [20, 21], "req_aprob_cursar": [12, 17], "req_aprob_rendir": [] },
  { "nro": 28, "nombre": "Teoría de la Información y la Comunicación", "anio": 4, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [19, 21], "req_aprob_cursar": [13], "req_aprob_rendir": [19, 21] },
  { "nro": 29, "nombre": "Calidad y Certificación del Proceso y del Producto de Software", "anio": 4, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [20, 21], "req_aprob_cursar": [17, 18], "req_aprob_rendir": [] },
  { "nro": 30, "nombre": "Auditoría Informática", "anio": 4, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [16, 25], "req_aprob_cursar": [12], "req_aprob_rendir": [] },
  { "nro": 31, "nombre": "Sistemas Inteligentes", "anio": 4, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [22, 23], "req_aprob_cursar": [12], "req_aprob_rendir": [] },
  { "nro": 32, "nombre": "Diseño y Paradigmas de Lenguajes", "anio": 4, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [19], "req_aprob_cursar": [13], "req_aprob_rendir": [19] },
  { "nro": 33, "nombre": "Seguridad de Sistemas Informáticos", "anio": 4, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [21, 22], "req_aprob_cursar": [18], "req_aprob_rendir": [21, 22] },
  { "nro": 34, "nombre": "Arquitectura de Software", "anio": 5, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [27], "req_aprob_cursar": [20], "req_aprob_rendir": [27] },
  { "nro": 35, "nombre": "Reingeniería de las Organizaciones y de los Sist. de Información", "anio": 5, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [25, 27], "req_aprob_cursar": [20, 21], "req_aprob_rendir": [25, 27] },
  { "nro": 36, "nombre": "Administración y Evaluación Financiera de Proyectos Informáticos", "anio": 5, "cuatrimestre": "1", "tipo": "obligatoria", "req_reg_cursar": [25], "req_aprob_cursar": [21], "req_aprob_rendir": [25] },
  { "nro": 37, "nombre": "Optativa (Mínimo 75 hs.)", "anio": 5, "cuatrimestre": "1", "tipo": "optativa", "req_reg_cursar": [], "req_aprob_cursar": [], "req_aprob_rendir": [] },
  { "nro": 38, "nombre": "Optativa (Mínimo 75 hs.)", "anio": 5, "cuatrimestre": "2", "tipo": "optativa", "req_reg_cursar": [], "req_aprob_cursar": [], "req_aprob_rendir": [] },
  { "nro": 39, "nombre": "Práctica Profesional Supervisada", "anio": 5, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [], "req_aprob_cursar": [], "req_aprob_rendir": [] },
  { "nro": 40, "nombre": "Proyecto Integrador", "anio": 5, "cuatrimestre": "2", "tipo": "obligatoria", "req_reg_cursar": [], "req_aprob_cursar": [], "req_aprob_rendir": [] }
];

module.exports = { materiasInformatica };
